### ISSUE TITLE
Having issue with netcat.py

### ISSUE THREAD

**Issue by Mellow-Cobra** [EONRaider/blackhat-python3#22]
Traceback (most recent call last):
  File "C:\Users\MMR3\Documents\Python\BlackHatPython\netcat.py", line 126, in <module>
    nc = NetCat(args, buffer.encode())
  File "C:\Users\MMR3\Documents\Python\BlackHatPython\netcat.py", line 24, in __init__
    self.socket.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR)
TypeError: setsockopt() takes exactly 3 arguments (2 given)

**Comment by Mellow-Cobra** [comment]
I figured this out you need to have 1 the int socket.setsockopt(level: ..., optname: ...,value: 1)
